### ISSUE TITLE
Explanation of some of the things you didn't understand!

### ISSUE THREAD

**Issue by ReiwuKleiwu** [Atagait/DrrrAPI#1]
Hello, 
I'm a moderator of drrr.com and I am pretty sure you know who I am. :D `Reimu#Q4OHAKUREI`
So I saw that you didn't quite understand what a few `user attributes` are used for, so I am going to explain what's going on.
```
player:(boolean - i don't know what this is for),
role:(string - i don't know what this is for),
visible:(boolean - i don't know what this is for),
alive:(boolean - i don't know what this is for)
```

Basically, there's a feature about rooms only moderators can activate on room creation which is called "Game Room". 
Those Game Rooms let you play the Werewolf game as far as I know..
Here's what the above mentioned attributes do: 

```
role:(string - not quite sure what this is used for yet),
visible: (boolean - not quite sure what this is used for yet),
```

player:(boolean - flags people who take part in the game) 
e.g.: 

True: ![True](https://i.imgur.com/n8jawqM.png)

False: ![False](https://i.imgur.com/pZqUrc4.png)

alive:(boolean - flags people who're alive) 
e.g.: 

True: ![True](https://i.imgur.com/qedGZRG.png)

False: ![False](https://i.imgur.com/IgYIm2g.png)

I hope I could you out a little. If you want me to open a game room for you, let me know. ^^
Great documentation btw, I used it for my last project. 
Thank you. 👍

**Comment by Atagait** [comment]
Thanks! I've added this information to `master` in  40d53d1
